name: gneiss
channels: !!python/tuple
- https://conda.anaconda.org/bioconda
- https://conda.anaconda.org/biocore
- https://conda.anaconda.org/qiime2
- defaults
dependencies:
- anaconda::matplotlib=1.5.1=np111py35_0
- anaconda::numexpr=2.6.1=np111py35_1
- anaconda::numpy=1.11.2=py35_0
- anaconda::pandas=0.19.1=np111py35_0
- anaconda::pytables=3.2.2=np111py35_4
- anaconda::scikit-bio=0.5.1=np111py35_0
- anaconda::scipy=0.18.1=np111py35_0
- bioconda::click=6.6=py35_0
- bokeh=0.12.4=py35_0
- bz2file=0.98=py35_0
- cachecontrol=0.11.6=py35_0
- contextlib2=0.4.0=py35_0
- cycler=0.10.0=py35_0
- decorator=4.0.10=py35_0
- entrypoints=0.2.2=py35_0
- flake8=2.5.1=py35_0
- freetype=2.5.5=1
- future=0.15.2=py35_0
- h5py=2.6.0=np111py35_1
- hdf5=1.8.16=0
- ipykernel=4.0.3=py35_0
- ipython=3.2.3=py35_0
- ipython_genutils=0.1.0=py35_0
- ipywidgets=4.1.1=py35_0
- jinja2=2.8=py35_1
- jsonschema=2.5.1=py35_0
- jupyter=1.0.0=py35_3
- jupyter_client=4.3.0=py35_0
- jupyter_console=5.0.0=py35_0
- jupyter_core=4.1.0=py35_0
- libpng=1.6.22=0
- lockfile=0.12.2=py35_0
- markupsafe=0.23=py35_2
- mccabe=0.3.1=py35_0
- mistune=0.7.2=py35_1
- mkl=11.3.3=0
- natsort=4.0.3=py35_0
- nbconvert=4.2.0=py35_0
- nbformat=4.0.1=py35_0
- nose=1.3.7=py35_1
- notebook=4.2.1=py35_0
- openssl=1.0.2h=1
- patsy=0.4.1=py35_0
- pep8=1.7.0=py35_0
- pip=8.1.2=py35_0
- prompt_toolkit=1.0.9=py35_0
- ptyprocess=0.5.1=py35_0
- pyflakes=1.2.3=py35_0
- pygments=2.1.3=py35_0
- pyparsing=2.1.4=py35_0
- pyqt=4.11.4=py35_3
- python=3.5.2=0
- python-dateutil=2.5.3=py35_0
- python.app=1.2=py35_4
- pytz=2016.4=py35_0
- pyyaml=3.12=py35_0
- pyzmq=15.2.0=py35_1
- qiime2::arrow=0.8.0=py35_0
- qiime2::binaryornot=0.3.0=0_ge797740
- qiime2::biom-format=2.1.5=py35_3
- qiime2::cookiecutter=1.4.0=py35_0
- qiime2::ijson=2.3=py35_0
- qiime2::ipymd=0.1.2=py35_0
- qiime2::jinja2-time=0.2.0=py35_0
- qiime2::poyo=0.4.0=py35_0
- qiime2::python-frontmatter=0.2.1=py35_0
- qiime2::tzlocal=1.3=py35_0
- qiime2::whichcraft=0.4.0=py35_0
- qt=4.8.7=3
- qtconsole=4.0.1=py35_0
- readline=6.2=2
- requests=2.10.0=py35_0
- setuptools=23.0.0=py35_0
- sip=4.16.9=py35_0
- six=1.10.0=py35_0
- sqlite=3.13.0=0
- statsmodels=0.8.0=np111py35_0
- terminado=0.6=py35_0
- tk=8.5.18=0
- tornado=4.3=py35_1
- traitlets=4.2.1=py35_0
- wcwidth=0.1.7=py35_0
- wheel=0.29.0=py35_0
- xz=5.2.2=0
- yaml=0.1.6=0
- zlib=1.2.8=3
- pip:
  - alabaster==0.7.9
  - appdirs==1.4.0
  - appnope==0.1.0
  - args==0.1.0
  - babel==2.3.4
  - backports.shutil-get-terminal-size==1.0.0
  - canvas==0.0.1
  - chest==0.2.3
  - clint==0.5.1
  - cloudpickle==0.2.1
  - colorama==0.3.7
  - coverage==4.1
  - coveralls==1.1
  - cvxopt==1.1.8
  - cython==0.23.5
  - dask==0.11.0
  - datashader==0.4.0
  - datashape==0.5.2
  - docopt==0.6.2
  - docutils==0.12
  - emperor==1.0.0b5
  - ete3==3.0.0b35
  - gneiss (/Users/mortonjt/Dropbox/UCSD/research/gneiss)==0.3.1
  - gnureadline==6.3.3
  - heapdict==1.0.0
  - igraph==0.1.11
  - imagesize==0.7.1
  - ipyparallel==5.2.0
  - ipython-genutils==0.1.0
  - jgraph==0.2.1
  - joblib==0.10.2
  - jupyter-client==4.3.0
  - jupyter-console==5.0.0
  - jupyter-core==4.1.0
  - llvmlite==0.14.0
  - locket==0.2.0
  - matplotlib-venn==0.11.4
  - msgpack-python==0.4.8
  - multipledispatch==0.4.8
  - nbdime==0.1.0
  - networkx==1.11
  - numba==0.29.0
  - odo==0.4.2
  - packaging==16.8
  - partd==0.3.6
  - path.py==8.1.2
  - pexpect==4.2.1
  - pickleshare==0.7.4
  - pillow==3.3.1
  - pkginfo==1.4.1
  - ply==3.9
  - prompt-toolkit==1.0.13
  - pulp==1.6.5
  - pyemd==0.3.0
  - pyomo==5.1.1
  - pysam==0.9.0
  - python-igraph==0.7.1.post6
  - python-ternary==1.0
  - pyutilib==5.4.1
  - q2-composition==2017.3.0.dev0
  - q2-feature-table==2017.3.0.dev0
  - q2-taxa==2017.3.0.dev0
  - q2-types==2017.3.0.dev0
  - q2cli (/Users/mortonjt/Dropbox/UCSD/research/q2/q2cli)==2017.3.0.dev0
  - q2templates==2017.3.0.dev0
  - qcli==0.1.1
  - qiime2 (/Users/mortonjt/Dropbox/UCSD/research/q2/qiime2)==2017.3.0.dev0
  - requests-toolbelt==0.7.0
  - rpy2==2.7.8
  - scikit-learn==0.17.1
  - seaborn==0.7.1
  - simplegeneric==0.8.1
  - snowballstemmer==1.2.1
  - sourcetracker==2.0.1.dev0
  - sphinx==1.4.9
  - tables==3.2.2
  - tabview==1.4.2
  - toolz==0.8.0
  - twine==1.8.1
  - xarray==0.8.2
  - xlrd==0.9.4

